### PR TITLE
Added POSTGRES

### PR DESCRIPTION
**Pull request by jamoski3112**
Postgres yet to be tested

### CODE REVIEW

**Comment by Tibinsunny** [comment]
Hi..Leet Bro I don't have my lap with me..Njan Lap kitumbolekkum code update cheyam :D

**Review by mufeedvh — APPROVED** [review]

**Comment by Tibinsunny** [comment]
@mufeedvh  @rahulr311295  guys oru error und..If the script is unable to get data from API, the  second try statement  for POSTGRES is supposed to run automatically[I think so].But the try statement with POSTGRES will not work unless a user KeyboardInterrupt is triggered. Which means,As soon as the code show the error "Error Retriving Data From API" it has to jump to next try statement automatically.It is not happening unless a KeyboardInterrupt is triggered
Athu fix cheyande...
Ente kayil Laptop illaa..atha scene :D

**Comment by jamoski3112** [comment]
@Tibinsunny will try

**Comment by Tibinsunny** [comment]
@rahulr311295  Ok :D

**Pull request merged**
